INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);
INSERT INTO users (name, age) VALUES ('Arthur', 4);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Example project', 'Generic', 3000, '01/01/00', '01/01/20');

INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 5);
